# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# See https://docs.coderabbit.ai/reference/configuration for all fields and default values
reviews:
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "sync(upstream)"
