pull_request_rules:
  - name: automatically merge approved PRs
    conditions:
      - base = main
      - "#approved-reviews-by >= 1"
      - check-success = "Go tests"
      - check-success = "Web tests"
      - check-success = "E2E (KinD)"
    actions:
      merge:
        method: squash
