pull_request_rules:
  - name: automatically merge approved PRs
    conditions:
      - base = main
      - "#approved-reviews-by >= 1"
      - check-success = "Tests"
      - check-success = "E2E"
    actions:
      merge:
        method: squash
