services:
  cuberouter-docs-user:
    image: harbor.isuanova.com/suanova/cuberouter-docs-user:${CUBEROUTER_IMAGE_TAG:-latest}
    container_name: cuberouter-docs-user
    restart: always
    ports:
      - "4080:80"
    environment:
      - TZ=Asia/Shanghai

  cuberouter-docs-admin:
    image: harbor.isuanova.com/suanova/cuberouter-docs-admin:${CUBEROUTER_IMAGE_TAG:-latest}
    container_name: cuberouter-docs-admin
    restart: always
    ports:
      - "4081:80"
    environment:
      - TZ=Asia/Shanghai
