apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pgo
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    postgres-operator.crunchydata.com/control-plane: postgres-operator
  name: pgo
