apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cube-router.fullname" . }}-config
  labels:
    {{- include "cube-router.labels" . | nindent 4 }}
data:
  BATCH_UPDATE_ENABLED: {{ .Values.config.BATCH_UPDATE_ENABLED | quote }}
  ERROR_LOG_ENABLED: {{ .Values.config.ERROR_LOG_ENABLED | quote }}
  NODE_TYPE: {{ .Values.config.NODE_TYPE | quote }}
  PORT: {{ .Values.config.PORT | quote }}
  TZ: {{ .Values.config.TZ | quote }}
  {{- range $key, $value := .Values.config.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.cubeRouter.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
