{{- if .Values.docs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cuberouter.fullname" . }}-docs
  labels:
    {{- include "cuberouter.selectorLabels" (dict "root" . "component" "docs") | nindent 4 }}
spec:
  type: {{ .Values.docs.service.type }}
  selector:
    {{- include "cuberouter.selectorLabels" (dict "root" . "component" "docs") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.docs.service.port }}
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cuberouter.fullname" . }}-docs
  labels:
    {{- include "cuberouter.selectorLabels" (dict "root" . "component" "docs") | nindent 4 }}
spec:
  replicas: {{ .Values.docs.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      {{- include "cuberouter.selectorLabels" (dict "root" . "component" "docs") | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "cuberouter.selectorLabels" (dict "root" . "component" "docs") | nindent 8 }}
    spec:
      containers:
        - name: docs
          image: "{{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag }}"
          imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          resources:
            {{- toYaml .Values.docs.resources | nindent 12 }}
{{- end }}
