{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cuberouter.fullname" . }}-app-pdb
  labels:
    {{- include "cuberouter.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.app.minAvailable }}
  selector:
    matchLabels:
      {{- include "cuberouter.selectorLabels" (dict "root" . "component" "app") | nindent 6 }}
{{- end }}
